package:
    name: haversine
    version: 0.4.5

source:
    fn: haversine-0.4.5.tar.gz
    url: https://pypi.python.org/packages/source/h/haversine/haversine-0.4.5.tar.gz
    md5: 555c853c2bd88fcad335dc910d176af4

build:
    noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - haversine

about:
    home: https://github.com/mapado/haversine
    license: MIT
    summary: Calculate the distance between 2 points on Earth

extra:
    recipe-maintainers:
        - ocefpaf
