{% set version = "2.2.0" %}

package:
  name: haversine
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/haversine/haversine-{{ version }}.tar.gz
  sha256: b710aaf32c442a6d04aa89678be55e3f6c11f9752fc01c216e89b13120b36269

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - haversine

about:
  home: https://github.com/mapado/haversine
  license: MIT
  summary: Calculate the distance between 2 points on Earth

extra:
  recipe-maintainers:
    - ocefpaf
