{% set version = "2.6.0" %}

package:
  name: haversine
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/haversine/haversine-{{ version }}.tar.gz
  sha256: eb7c308ba721e86662c1d50427cb9b06f9e7eb9984803d9ec200582425cc4fb7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    # - enum34  # [py<34]

test:
  imports:
    - haversine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mapado/haversine
  license: MIT
  license_file: LICENSE
  summary: Calculate the distance between 2 points on Earth

extra:
  recipe-maintainers:
    - ocefpaf
