{% set version = "1.0.2" %}

package:
  name: haversine
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/haversine/haversine-{{ version }}.tar.gz
  sha256: 63b9ceb3d2992314fe74948f57afd7d0fb623663ca32f2973565156aa34b9c52

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - haversine

about:
  home: https://github.com/mapado/haversine
  license: MIT
  summary: Calculate the distance between 2 points on Earth

extra:
  recipe-maintainers:
    - ocefpaf
