{% set version = "1.0.1" %}

package:
  name: haversine
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/haversine/haversine-{{ version }}.tar.gz
  sha256: 6e13332a9bcab2e902f5c7d2fd3085959a32ede673bbfa8aa5aad1e0aaf686ee

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - haversine

about:
  home: https://github.com/mapado/haversine
  license: MIT
  summary: Calculate the distance between 2 points on Earth

extra:
  recipe-maintainers:
    - ocefpaf
