# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "0/ms5Hk3BcgwaPNYiee6aicevK6ms23uNY3uIgFNwJmNw69ABja2Qmjtgukl1dgX/vnQ2XfgjAiXa9oNGqbyWYHEwSPVn/1lWTRIjhluZMSfP56r98UKdjp/1zwtF/OdHLezkgjgxeBZ2TC5Me38aFc/O/FMt4cOwOnhgJL957MKdhRGAcghaTUIQ9/Gtd0CTUl86Cs3/S/trimrxkS5fZzNaMSwM1qtnOu57l+l0CeffV6ZHzPCiQ6V8XpiQuL2sLJSI7b3gVJv1tGpfBM3/vpO9lxWNIOH+C4GaRoP9Y5E5tsK3pkPbbEAUTNzia/ioQZ13xTgsdnAxYzCKBwclsoyN6GNv0e5YrlVF9BSThgdpRgYtl6jDS4zBuQRqyDYcIIOyN+cG4/O4KbC21E54Y6mKCckh8s5zH5oLIzQWR5gAma3VU10vJ3Y0tNzr4vXohaNZBrg3rUIlBEi/qBrVpXTHVSnPCJepv36CHtA7tm4cnzjdJasRfj88mpa/0azmlo66pwAjxIMkrRw3nmWwBO2f1Ky/W162ak7y64oxAjwJCl81aAhHZ+RAl+fO/derry7d0DDGIDS7mrdxuCq0K1ZI7Cs5BEZklby7lfxbThDXV7vEcVmVZjp9TfCN47s5laO0wMaOq0ywHMn44me+81c6DJ0PwN3HpNOkm6b1Io="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
