travis:
  secure:
    BINSTAR_TOKEN: geDA4Tw35w7cooZvdXXG0hV/DO2eTmpWibFy2sCso8O55d378lyemqdojBmw3OuxH2ql+di0XU21DVNifmoSPhHHgZvaIBZ8LBwckHCwC2iAJvouuv9QVh2hl+oFmoAk6MhmrfgkRHtM0e11aohkCaA6Qkk87rCTakXLpKxR1RRy5XjL1DNv/x0alsgCjvMv7uJzjoYqSF+B0wQpoAdnva+h81NoQ5F3vcPhAFXOXv29Mlro/P1U9Sk4FBO2AP5YUoA7ME+A8DGYN4FoDj/6G4AwzQJ45qfMU2uvqOercZGZywwzens/SJFP9tL9Sfnyb29EKO7oBOfNY59U1J/PPPTGbphRYkB6tDSPG1sDhJ/dFk6o+I8CotBjYgSO4n4r9XXg7cmuG4wRFXeciQV9bBCncBp8LejyyWw8EjnPZuqFZD1Huwoz0WbZew7dgECKfBKadueHwOFrwYJb76kMe+IPm410hqNdjSQetrscnWAAt+u5bnVUfGE7QmUE37dgJ00fDmwVeh5l+wDmvol3uRz1jhx1FWp+K2qEBjgq/NpIPjUAyb2dfZ3OWeGjaYnWxBp4w64TnuAqcr8COflMU4REgZmgxtnbq76GpWXuCNe4IQ8wUx+5triCXI97j6ZmXaI3CcPuGAftwd/bNSd58jI4RdXZZi4FGEyiGerC7v4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
