travis:
  secure:
    BINSTAR_TOKEN: 0/ms5Hk3BcgwaPNYiee6aicevK6ms23uNY3uIgFNwJmNw69ABja2Qmjtgukl1dgX/vnQ2XfgjAiXa9oNGqbyWYHEwSPVn/1lWTRIjhluZMSfP56r98UKdjp/1zwtF/OdHLezkgjgxeBZ2TC5Me38aFc/O/FMt4cOwOnhgJL957MKdhRGAcghaTUIQ9/Gtd0CTUl86Cs3/S/trimrxkS5fZzNaMSwM1qtnOu57l+l0CeffV6ZHzPCiQ6V8XpiQuL2sLJSI7b3gVJv1tGpfBM3/vpO9lxWNIOH+C4GaRoP9Y5E5tsK3pkPbbEAUTNzia/ioQZ13xTgsdnAxYzCKBwclsoyN6GNv0e5YrlVF9BSThgdpRgYtl6jDS4zBuQRqyDYcIIOyN+cG4/O4KbC21E54Y6mKCckh8s5zH5oLIzQWR5gAma3VU10vJ3Y0tNzr4vXohaNZBrg3rUIlBEi/qBrVpXTHVSnPCJepv36CHtA7tm4cnzjdJasRfj88mpa/0azmlo66pwAjxIMkrRw3nmWwBO2f1Ky/W162ak7y64oxAjwJCl81aAhHZ+RAl+fO/derry7d0DDGIDS7mrdxuCq0K1ZI7Cs5BEZklby7lfxbThDXV7vEcVmVZjp9TfCN47s5laO0wMaOq0ywHMn44me+81c6DJ0PwN3HpNOkm6b1Io=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
