travis:
  secure:
    BINSTAR_TOKEN: Bxd5+Hs+WK2UNkrfNeA+LRcHPVPTauIrC9q21i5/+AIjmwhHdvLwABSQ8CGgkB43FQuMmaI2As8w76wCKn2UdzIR7w4gfKWQcXMxIkhBGtplncuf3ecWu1HJylz33gjhdRI+UYb4asfUUMH4x3JcrMK85DmRnmhzKi1lwwoK5xWEJ8B+5vZ+JVrtcDzfz0waqV1FHnc/q68DDRElxDZNaKuEeGdVgQVIkvnNZyi1lYUx16aNbPhhwNCMxcMn2aRgJkEs8Ci/jBzKf9zcbkd6DYo9GCknMf4jmK5GJwWb37cK2osbzyS0rQM30vkAZI9B/azQcjIPoTsUpe83OLGvR9kWukxtDMSFm+scJFM01HKZM3uZ5AXAk4/BENOTWsh/7kLbsEUqctqnl4rwGBS2Pcx9kB8cBhkyFfylGHW05oFxCE3zBIX1na2G2toI1mPmvvQuCwvrU29YwGqlyLJMjNOL2jT1kYivWBLvzgeDU50TJaF97+SPCUjXZZNciYClmDBMV69QSMNRGiAg6bZDGAU//a3M9VfKsUVJ1cJzNxjVRipbqBJafl4KwYwW1AVKFMGqlwL+yeFUSgYfPLRjzzlbbjgvdl3U9e3akG48wovck3avJXLpbxB/reSjopvr9EfdRooYGI6dpxCbPsZYLXyBsR6BBqDPpcM1ylA5cvI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
